@startuml
'https://plantuml.com/class-diagram

Class Coordinate {}
Class Robot {}
Class RobotMapper {
    + robotCoordinateHashMap: HashMap<Robot, Coordinate>
    + getCoordinate(robot: Robot): Coordinate
}

RobotMapper --> Robot
RobotMapper --> Coordinate

Class Planet {}
Class Cell {}

Planet *-- "0..*" Cell : List[List[Cell]]

@enduml