@startuml
'https://plantuml.com/class-diagram

class InterMediator {
    -robotMapper: RobotMapper
    -robots: Robot[]
    -planet: Planet
    -shockWaves: ShockWave[]
    -commands: InterMediatorCommand[]
    +executeCommands()
}


package Commands {
    abstract class InterMediatorCommand {
        +execute()
    }

    InterMediator -> InterMediatorCommand

    package RobotCommands {
        abstract class RobotCommand extends InterMediatorCommand {
            -planet: Planet
            -robot: Robot
            -robotMapper: RobotMapper
        }

        class MoveRobotCommand extends RobotCommand {
            -direction: Direction
        }

        class ConstructPipeCommand extends RobotCommand {}
        class CultivateCommand extends RobotCommand {}

        abstract class ExtractCommand extends RobotCommand {}

        class ExtractOreCommand extends ExtractCommand {}
        class ExtractFoodCommand extends ExtractCommand {}
    }

    package shockWaveCommands {
        abstract class ShockWaveCommand extends InterMediatorCommand {
            -shockWave: ShockWave
            -planet: Planet
        }

        class PropagationShockWaveCommand extends ShockWaveCommand {}
    }

    package PlanetCommands {
        abstract class PlanetCommand extends InterMediatorCommand {
            -planet: Planet
            -localisation: Coordinate
            -robotMapper: RobotMapper
        }

        class MutatePlanetCommand extends PlanetCommand {}
    }
}

@enduml