@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Presenter
participant Sequencer
participant InterMediator
participant Shockwave
participant Planet
participant Robot

loop until age limit
    Presenter -> Sequencer ++ : step
    Sequencer -> InterMediator ++ : Shockwave turn
        loop for all shockwaves
            InterMediator -> Shockwave ++ : propagate
            InterMediator <- Shockwave -- : propagation result
        end
    Sequencer <- InterMediator -- : response to shockwave turn

    Sequencer -> InterMediator ++ : Planet turn
    InterMediator -> Planet ++ : react
    InterMediator <- Planet -- : reaction result
    Sequencer <- InterMediator -- : response to planet turn

    Sequencer -> InterMediator ++: Robot turn
        loop for all robots
            InterMediator -> Robot ++ : compute
            InterMediator <- Robot -- : computation result
        end
    Sequencer <- InterMediator -- : response to robot turn
    Presenter <- Sequencer -- : end step
end

@enduml